## 에러 처리

- 에러가 발생하지 않는 코드를 작성하는 것을 불가능하다.
- 직접적으로 에러를 발생하지 않는 예외적인 상황에 적절하게 대응하지 않으면 에러로 이어질 가능성이 크다.
- 따라서 에러나 예외 상황이 발생할 수 있다는 것을 전제하고 이에 대응하는 코드를 작성하는 것이 중요하다.

### 1. try ... catch ... finally 문

- finally 문은 생략이 가능하지만 catch 문이 없는 try 문은 의미가 없으므로 생략하지 않는다.

```jsx
try {
  // 실행할 코드 (에러가 발생할 가능성이 있는 코드)
} catch (err) {
  // err가 방생하면 try 코드 블록에서 발생한 Error 객체가 전달된다.
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행된다.
}
```

### 2. Error 객체

- Error 생성자 함수는 에러 객체를 생성하고, 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있다.

`const error = new Error('invalid');`

- 자바스크립트는 Error 생성자 함수를 포함 총 7가지의 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공한다.

|생성자 함수|인스턴스|
|:--:|:--:|
|Error|일반적 에러 객체|
|SyntaxError|js 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체|
|ReferenceError|참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체|
|TypeError|피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체|
|RangeError|숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체|
|URIError|encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체|
|EvalError|eval 함수에서 발생하는 에러 객체|

### 3. throw 문

- Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다. (에러 객체 생성 !== 에러 발생)
- 에러를 발생시키려면 try 코드 블록에서 throw 문으로 에러 객체를 던져야 한다.

```jsx
try {
  throw new Error('something wrong');
} catch (err) {
  console.log(err);
}
```

### 4. 에러의 전파

- 에러는 호출자 방향으로 전파된다. (콜 스택의 아래방향으로)
- throw된 에러를 캐치하지 않으면 호출자 방향으로 전파된다. (어디에서도 캐치하지 않으면 프로그램은 강제 종료된다.)

![image](https://github.com/6uamy/modern-javascript-study/assets/79950091/52c80932-9625-41b0-9a44-872320b901d0)

🌠  비동기 함수인 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없다.
=> 콜 스택에 푸시된 콜백 함수의 실행 컨텍스트는 콜 스택의 가장 하부에 존재하여, 에러를 전파할 호출자가 존재하지 않는다.















